# Generated by Django 5.2.7 on 2025-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=250, unique=True)),
                ('cantidad_horas_curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=250)),
                ('apellido_estudiante', models.CharField(max_length=250)),
                ('edad_estudiante', models.IntegerField()),
                ('nota_curso_estudiante', models.IntegerField()),
                ('cursos', models.ManyToManyField(related_name='estudiantes', to='estudiante.curso')),
            ],
        ),
    ]
