# Generated by Django 5.2.7 on 2025-10-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_cursos_alter_estudiante_curso_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nota_curso_estudiante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
