# Generated by Django 5.2.7 on 2025-10-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.TextField(max_length=250, unique=True)),
                ('cantidad_horas_curso', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.TextField(max_length=250, unique=True)),
                ('apellido_estudiante', models.TextField(max_length=250, unique=True)),
                ('edad_estudiante', models.IntegerField(unique=True)),
                ('nota_curso_estudiante', models.IntegerField(blank=True)),
                ('curso_estudiante', models.TextField(blank=True)),
            ],
        ),
    ]
