# Generated by Django 5.2.7 on 2025-10-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(related_name='estudiantes', to='estudiante.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso_estudiante',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
